# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamination',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начат'),
        ),
    ]
