# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userexamination_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamination',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закончен'),
        ),
    ]
