# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170515_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_test_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_test_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
