# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170517_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexaminationquestionlog',
            name='sum_points',
            field=models.BooleanField(default=True, verbose_name='Суммировать баллы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_test_time',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего учёта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='next_test_time',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего учёта'),
        ),
    ]
