# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170517_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexaminationquestionlog',
            name='sum_points',
        ),
        migrations.AddField(
            model_name='question',
            name='sum_points',
            field=models.BooleanField(default=True, verbose_name='Суммировать баллы'),
            preserve_default=False,
        ),
    ]
